const AuthType = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
};

const ProductType = {
  ADD_PRODUCT: "ADD_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  GET_PRODUCTS: "GET_PRODUCTS",
};

const CartType = {
  GET_USERCART: "GET_USERCART",
  ADD_CART: "ADD_CART",
  EDIT_CART: "EDIT_CART",
};

export { AuthType, ProductType, CartType };
